from selenium_tests.pages.subscription_home_page import subscription_home_page
from selenium_tests.pages.verify_cart_quantity_page import verify_cart_quantity_page
from selenium_tests.pages.place_order_register_before_checkout_page import place_order_register_before_checkout_page

def test_place_order_register_before_checkout(driver):

    place_order_page = place_order_register_before_checkout_page(driver)
    place_order_page.register_first_then_checkout()
